### ISSUE TITLE
Create Wireframing - Mockup

### ISSUE THREAD

**Issue by fabiodearaujo** [Paddy-Hack-Team/happypaddygo#2]
To Create the landing page wireframing - mockup on Desktop and mobile views.

**Comment by Joan-Amudu** [comment]
Creating Wireframes for Mobile, Tablet and Desktop Users.

**Comment by Joan-Amudu** [comment]
[Happy-Paddy-Go-Wireframes.pdf](https://github.com/Paddy-Hack-Team/happypaddygo/files/6086763/Happy-Paddy-Go-Wireframes.pdf)

**Comment by Joan-Amudu** [comment]
Wireframes complete

**Comment by fabiodearaujo** [comment]
![image](https://user-images.githubusercontent.com/52252478/110034963-f8be7400-7d32-11eb-8a03-ddee1b3d0021.png)

**Comment by fabiodearaujo** [comment]
![image](https://user-images.githubusercontent.com/52252478/110035103-23103180-7d33-11eb-89bc-8bc2ec1d2fee.png)

**Comment by fabiodearaujo** [comment]
![image](https://user-images.githubusercontent.com/52252478/110035176-3b804c00-7d33-11eb-8274-c61bbb51ce07.png)
