### ISSUE TITLE
Create the About St Patrick's Day Page

### ISSUE THREAD

**Issue by fabiodearaujo** [Paddy-Hack-Team/happypaddygo#5]
aboutpaddy.html

**Comment by Joan-Amudu** [comment]
Created About Paddy, html page.

**Comment by Joan-Amudu** [comment]
Created video gallery content

**Comment by Joan-Amudu** [comment]
Added footer and image carousel

**Comment by Joan-Amudu** [comment]
Changed image carousel to slider using materialize and re-arranged video content.

**Comment by Joan-Amudu** [comment]
Adding quotes to the images in slider

**Comment by Joan-Amudu** [comment]
Stylied quotes in images slider with overlay and added font-weight

**Comment by Joan-Amudu** [comment]
Aligned footer social media icons  and copyright info to center.

**Comment by Joan-Amudu** [comment]
Created space around videos using padding in css to create a more visually apealing look.
